namespace CS01_41_Loops_While
{
    class Program
    {
        static void Main(string[] args)
        {
            /* WHILE LOOP
			 * 
			 * while loop repeatedly executes same set of statements as long as condition is true.
             * while döngüsü, koşul doğru olduğu sürece aynı ifade grubunu tekrar tekrar yürütür.
			 * 
			 * condition is checked at loop start.
             * döngü başlangıcında koşul kontrol edilir.
			 * 
			 * the code is repeated in a loop is called the body of the loop
			 * Bir döngüde tekrarlanan koda döngünün gövdesi denir.
             * 
			 * Each repetition of the loop body is called an iteration of the loop.
             * Each repetition of the loop body is called an iteration of the loop.
			 */

            #region Syntax & General Usage | Syntax & Genel Kullanım

            // while (true) 
            // {
            //     
            // }

            #endregion

            #region Example Usage | Örnek Kullanım
			// Print the numbers between 1-10 | 1-10 arasındaki sayıları ekrana yazdırma
            
			// With for loop | For döngüsü ile birlikte
			Console.WriteLine("-----> With for loop | For döngüsü ile birlikte <-----");
			for (int i = 1; i <= 10; i++)
            {
	            Console.Write(i);
            }
			
			Console.WriteLine("\n-----> With for While | While döngüsü ile birlikte <-----");
            int counter = 1;
            while (counter <= 10)
            {
	            Console.Write(counter);
	            counter++;
            }
            #endregion

            #region Example 1 | Örnek 1
            Console.WriteLine("\n-----> Example 1 | Örnek 1 <-----");
            // using a loop , iterate untill we have 10 students in the room

            int numberOfStudents = 1;

            while (numberOfStudents <= 10) {
	            Console.WriteLine("Student " + numberOfStudents);
	            numberOfStudents++;
            }
            #endregion

            #region Example 2 | Örnek 2
            Console.WriteLine("\n-----> Example 2 | Örnek 2 <-----");
			// print 11,10,9,8......1

            int num = 11;
            while (num >= 1) {
	            Console.Write(num + " ");
	            num--;
            }
            #endregion

            #region Example 3 | Örnek 3
            Console.WriteLine("\n-----> Example 3 | Örnek 3 <-----");
            // Write a program using while loop, that calculates the sum of the even numbers between 0 and 100
            // 0 ile 100 arasındaki çift sayıların toplamını bulan bir program yazın
            int ex3 = 0;
            int sumEven = 0;
            while (ex3 < 100) {
	            if (ex3 % 2 == 0) {
		            sumEven = sumEven + ex3;
		            // Console.WriteLine(ex3);
	            }
	            ex3++;
            }
            Console.WriteLine(sumEven);
            #endregion
            
            #region Example 4 | Örnek 4
            Console.WriteLine("\n-----> Example 4 | Örnek 4");
            // Take a number from the user, decrement each number by 1 and print it to the screen till the number 0.
            // Kullanıcıdan bir sayı alın, her sayıyı 1 azaltın ve 0 sayısına kadar ekrana yazdırın.
            Console.WriteLine("Please Enter a number between 1-10");
            int userInput = Convert.ToInt32(Console.ReadLine());
            int counter1 = userInput;

            while (counter1 != 0)
            {
	            Console.Write(counter1);
	            counter1--;
            }
            #endregion
            
            #region Example 5 | Örnek 5
            Console.WriteLine("\n-----> Example 5 | Örnek 5");
            Console.WriteLine("Enter numbers for find the sum | Toplamını bulmak istediğiniz sayıları giriniz.");
            Console.WriteLine("-1 will stop the process | -1 prosesi durdurur.");
            int counterEx5 = 0;
            while (true)
            {
	            int userInput5 = Convert.ToInt32(Console.ReadLine());
	            if (userInput5 < 0)
	            {
		            break;
	            }
	            else
	            {
		            counterEx5 = counterEx5 + userInput5;
	            }
            }
            Console.WriteLine("Sum | Toplam : {0}", counterEx5);
            #endregion

            #region Example 6 | Örnek 6
            // 1-10 arasında oluşturulan rastgele sayıyı kullanıcının tahmin etmesini isteyen bir uygulama yazın.
            // Write an application that asks the user to guess a randomly generated number from 1-10.
            Console.WriteLine("\n0-10 arasında sistem tarafından üretilen rastgele sayıyı tahmin edin. 3 Deneme Hakkınız var!");
            Console.WriteLine("Guess the random number generated by the system from 0 to 10. U have 3 Turn for find.");
            Console.WriteLine("Please enter your guess | Lütfen tahmininizi girin.");
            
            int guess = 0;
            Random rnd = new Random();
            guess = rnd.Next(10);
            int counter6 = 0;
            while (true)
            {
	            if (counter6 == 3)
	            {
		          break;
	            }
	            else
	            {
		            int userInput6 = Convert.ToInt32(Console.ReadLine());

		            if (userInput6 == guess)
		            {
			            Console.WriteLine("Congrats! | Tebrikler");
			            break;
		            }
		            else
		            {
			            Console.WriteLine("Try Again | Yeniden deneyin");
		            }

		            counter6++;
	            }
            }

            #endregion
        }
    }
}